### ISSUE TITLE
AutoUpdate Error

### ISSUE THREAD

**Issue by moskovskayax3** [ExLibrisGroup/alma-print-daemon#30]
We have received feedback from our users that a "A new update is available. Downloading now" appears in the Alma Print Daemon and no longer disappears.

![grafik](https://user-images.githubusercontent.com/60343703/119989907-0436d980-bfc8-11eb-8d56-1a887436116f.png)

I have looked at the error and found several 404 errors. These occur when trying to download.
I assume it has typos in it.

Logfile download address: https://github.com/ExLibrisGroup/alma-print-daemon/releases/download/v2.0.0-beta/alma-print-daemon-Setup-2.0.0-beta.exe.blockmap

Github publications link: https://github.com/ExLibrisGroup/alma-print-daemon/releases/download/v2.0.0-beta/alma-print-daemon.Setup.2.0.0-beta.exe.blockmap

and

Logfile download address: https://github.com/ExLibrisGroup/alma-print-daemon/releases/download/v2.0.0-beta/alma-print-daemon-Setup-2.0.0-beta.exe

Github publications link: https://github.com/ExLibrisGroup/alma-print-daemon/releases/download/v2.0.0-beta/alma-print-daemon.Setup.2.0.0-beta.exe

Both have a typo in "daemon-Setup-2.0.0" instead of "daemon.Setup.2.0.0".

log: [main.log](https://github.com/ExLibrisGroup/alma-print-daemon/files/6561092/main.log)

Is this a known problem or is it unique to us? If it's just us, I'll just install the new version everywhere via script.

**Comment by mgobat** [comment]
Interesting....this is the first I've heard of this, but did just replicate the problem. I installed 1.3, and sure enough, it is trying to download a new version. I didn't think it would find a new version, with version 2.0 being flagged as pre-release. Thanks for reporting this. Looking into it now.

**Comment by moskovskayax3** [comment]
@mgobat I myself do not use the software directly. I am the IT supporter/responsible person and only manage the deployment of the software. 

I have briefly checked some devices. Many are currently on version 1.2 and all devices want to download beta version 2.0. We deployed company wide version 1.1 earlier this year. (Standard installation, just give a customized alma-print-config.json with it).  

I get the message for the update on all known versions. (1.1/1.2) So far I have not found any device on version 1.3. But because of covid the library computers are not always on.

I checked the log of a 1.2 installation more closely. The update to 1.3 could not be done there already.

```
[2021-04-01 10:02:43.851] [info] Checking for update
[2021-04-01 10:02:45.608] [info] Found version 1.3.0 (url: alma-print-daemon-Setup-1.3.0.exe)
[2021-04-01 10:02:45.616] [info] Downloading update from alma-print-daemon-Setup-1.3.0.exe
[2021-04-01 10:02:45.626] [debug] updater cache dir: C:\Users\username_removed\AppData\Local\alma-print-daemon-updater.
[2021-04-01 10:02:45.647] [info] Cached update sha512 checksum doesn't match the latest available update. New update must be downloaded. Cached: HypBc71uv4rIk3qxxKD7IpSHuQEhU618uDe8oE1vaoB6/W08xmw5gTxe4coKfJt8BUnBQ8YJe5Gdy9KpF4JUeg==, expected: 6ySd0UZfvg/zC78eHrMKMAAnGqzQF9vy7FKiYltObF/9Vk2a12Pss7w8IiN8o2i7FUwohl0UpGno21Ceebc21Q==. Directory for cached update will be cleaned
[2021-04-01 10:02:45.659] [info] Download block maps (old: "https://github.com/ExLibrisGroup/alma-print-daemon/releases/download/v1.2.0/alma-print-daemon-Setup-1.2.0.exe.blockmap", new: https://github.com/ExLibrisGroup/alma-print-daemon/releases/download/v1.3.0/alma-print-daemon-Setup-1.3.0.exe.blockmap)
[2021-04-01 10:02:45.817] [error] Cannot download differentially, fallback to full download: Error: Cannot download "https://github.com/ExLibrisGroup/alma-print-daemon/releases/download/v1.3.0/alma-print-daemon-Setup-1.3.0.exe.blockmap", status 404: 
    at ClientRequest.<anonymous> (C:\Users\username_removed\AppData\Local\Programs\alma-print-daemon\resources\app.asar\node_modules\builder-util-runtime\out\httpExecutor.js:280:26)
    at ClientRequest.emit (events.js:223:5)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:93:6152)
    at SimpleURLLoaderWrapper.emit (events.js:223:5)
[2021-04-01 10:02:45.975] [error] Error: Error: Cannot download "https://github.com/ExLibrisGroup/alma-print-daemon/releases/download/v1.3.0/alma-print-daemon-Setup-1.3.0.exe", status 404: 
    at ClientRequest.<anonymous> (C:\Users\username_removed\AppData\Local\Programs\alma-print-daemon\resources\app.asar\node_modules\builder-util-runtime\out\httpExecutor.js:280:26)
    at ClientRequest.emit (events.js:223:5)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:93:6152)
    at SimpleURLLoaderWrapper.emit (events.js:223:5)
```

```
[2021-04-08 10:10:07.583] [info] Checking for update
[2021-04-08 10:10:09.471] [info] Found version 2.0.0-beta (url: alma-print-daemon-Setup-2.0.0-beta.exe)
[2021-04-08 10:10:09.478] [info] Downloading update from alma-print-daemon-Setup-2.0.0-beta.exe
[2021-04-08 10:10:09.486] [debug] updater cache dir: C:\Users\username_removed\AppData\Local\alma-print-daemon-updater
[2021-04-08 10:10:09.497] [info] Download block maps (old: "https://github.com/ExLibrisGroup/alma-print-daemon/releases/download/v1.2.0/alma-print-daemon-Setup-1.2.0.exe.blockmap", new: https://github.com/ExLibrisGroup/alma-print-daemon/releases/download/v2.0.0-beta/alma-print-daemon-Setup-2.0.0-beta.exe.blockmap)
[2021-04-08 10:10:09.672] [error] Cannot download differentially, fallback to full download: Error: Cannot download "https://github.com/ExLibrisGroup/alma-print-daemon/releases/download/v2.0.0-beta/alma-print-daemon-Setup-2.0.0-beta.exe.blockmap", status 404: 
    at ClientRequest.<anonymous> (C:\Users\username_removed\AppData\Local\Programs\alma-print-daemon\resources\app.asar\node_modules\builder-util-runtime\out\httpExecutor.js:280:26)
    at ClientRequest.emit (events.js:223:5)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:93:6152)
    at SimpleURLLoaderWrapper.emit (events.js:223:5)
[2021-04-08 10:10:09.824] [error] Error: Error: Cannot download "https://github.com/ExLibrisGroup/alma-print-daemon/releases/download/v2.0.0-beta/alma-print-daemon-Setup-2.0.0-beta.exe", status 404: 
    at ClientRequest.<anonymous> (C:\Users\username_removed\AppData\Local\Programs\alma-print-daemon\resources\app.asar\node_modules\builder-util-runtime\out\httpExecutor.js:280:26)
    at ClientRequest.emit (events.js:223:5)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:93:6152)
    at SimpleURLLoaderWrapper.emit (events.js:223:5)
```

**Comment by mgobat** [comment]
New release, 1.3.1, should fix this problem. Anyone not running the 2.0 beta version should get 1.3.1 the next time they start the Alma Print Daemon.
