### ISSUE TITLE
EPIPE Error

### ISSUE THREAD

**Issue by rsirres** [ExLibrisGroup/alma-print-daemon#38]
**Context**: We are migrating from Aleph to Alma and need to setup printers. 

When the print daemon (2.0.0-beta2 on windows 10 enterprise) is about to print I receive the following error message in the command line:
```
Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:149:25)
    at writeGeneric (internal/stream_base_commons.js:140:3)
    at Socket._writeGeneric (net.js:776:11)
    at Socket._write (net.js:788:8)
    at doWrite (_stream_writable.js:435:12)
    at writeOrBuffer (_stream_writable.js:419:5)
    at Socket.Writable.write (_stream_writable.js:309:11)
    at PDF.PdfExec [as exec] (C:\Program Files\alma-print-daemon\resources\app.asar\node_modules\html-pdf\lib\pdf.js:141:15)
    at PDF.PdfToFile [as toFile] (C:\Program Files\alma-print-daemon\resources\app.asar\node_modules\html-pdf\lib\pdf.js:83:8)
    at C:\Program Files\alma-print-daemon\resources\app.asar\main.js:48:13 {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
```

Have you already faced this issue ?

**Comment by rsirres** [comment]
After updating Windows 10 to the latest versions The error did not occur again.
