### ISSUE TITLE
Error blocking the proper function of the deamon

### ISSUE THREAD

**Issue by cybermo** [ExLibrisGroup/alma-print-daemon#65]
The error below occured and blocked the printing of pedning documents.

Version: Alma Print Daemon 2.1.0-beta3

```
Entered printDocumentsViaBrowser
Back from getDocuments; total_record_count = 0
No docs at all..set the timer
Timer triggered
Entered printDocumentsViaBrowser
(node:8648) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (C:\Program Files\alma-print-daemon\resources\app.asar\node_modules\almarestapi-lib\alma.js:60:18)
    at Request.self.callback (C:\Program Files\alma-print-daemon\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:223:5)
    at Request.<anonymous> (C:\Program Files\alma-print-daemon\resources\app.asar\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:223:5)
    at IncomingMessage.<anonymous> (C:\Program Files\alma-print-daemon\resources\app.asar\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:312:28)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
(node:8648) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8648) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mgobat** [comment]
@cybermo, do you get this error consistently, or was it a one time issue? Thanks.
